### ISSUE TITLE
org-mode's "code" snippet is outdated

### ISSUE THREAD

**Issue by xiongtx** [AndreaCrotti/yasnippet-snippets#110]
In `org-mode` 8.2.10, code blocks are defined as follows:

     #+NAME: <name>
     #+BEGIN_SRC <language> <switches> <header arguments>
       <body>
     #+END_SRC

The `code` template still uses

	#+begin_${1:lang} ${2:options}
	$0
	#+end_$1
	
However, I'm not sure either is necessary, since Org-mode has its own Easy Template (`<s`) that inserts:

	#+BEGIN_SRC 

	#+END_SRC

**Comment by AndreaCrotti** [comment]
yeah actually never quite liked using yasnippet with org-mode anyway, didn't know about this shortcut thanks I'll remove the snippet
