### ISSUE TITLE
Can Personal Snippets Overriding Bundled Without Prompt on Expansion?

### ISSUE THREAD

**Issue by sshaw** [AndreaCrotti/yasnippet-snippets#115]
Currently when I override a bundled snippet I get a prompt on expansion that allows me to choose between my local version and the overridden version. The [docs say](http://capitaomorte.github.io/yasnippet/snippet-organization.html#sec-2):

> Collections appearing earlier in the list override snippets with same names appearing in collections later in the list. yas-new-snippet always stores snippets in the first collection.

My snippets dir comes before the bundled dir in `yas-snippet-dirs`. Given this the docs imply that there would be no prompt. 

Bug or feature? In ether case how to get rid of the prompt?

**Comment by npostavs** [comment]
It's a feature to prompt if there are multiple snippets with the same key. You can `(setq yas-prompt-functions '(yas-no-prompt))` if you don't want it. Another possibility is to make your snippets have the same `#:name` or `#:uuid` as the one you want to override.

**Comment by sshaw** [comment]
>  Another possibility is to make your snippets have the same #:name 

Ah yes, I thought they did -but they didn't; user error :exclamation:. 

Thanks!
