### ISSUE TITLE
yasnippet" Discovered there was already *load* in fundamental-mode

### ISSUE THREAD

**Issue by mambolevis** [AndreaCrotti/yasnippet-snippets#119]
Hi,
The following problem appears when loading. I could not find any solution. How can I fix it?

[yas] Discovered there was already *scratch* in fundamental-mode
[yas] Discovered there was already  *code-conversion-work* in fundamental-mode
[yas] Discovered there was already  *load* in fundamental-mode
[yas] Discovered there was already  *Echo Area 0* in fundamental-mode
[yas] Discovered there was already  *Echo Area 1* in fundamental-mode
[yas] Discovered there was already  *load*-275874 in fundamental-mode

Regards,

Levis

**Comment by npostavs** [comment]
I don't think it's a problem. You can try setting `yas-verbosity` to a lower number if the messages annoy you.

**Comment by mambolevis** [comment]
Thank you!
