### ISSUE TITLE
js-mode function

### ISSUE THREAD

**Issue by transtone** [AndreaCrotti/yasnippet-snippets#120]
```function${1: ${2:name}}(${3:arg}) {
         $0
}```
maybe add a space is better
```function ${1: ${2:name}}(${3:arg}) {
         $0
}```

**Comment by npostavs** [comment]
I don't see a space between `function` and the arglist in the examples at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions, and 2 spaces between `function` and the name would be bad.

**Comment by AndreaCrotti** [comment]
yeah agreed @npostavs thanks anyway
