### ISSUE TITLE
Haskell-mode pragma snippet is a huge pain with autopairing braces

### ISSUE THREAD

**Issue by kozross** [AndreaCrotti/yasnippet-snippets#124]
As someone who programs in several curly-brace languages as well as Haskell, the pragma snippet of '{' is really annoying for me to use, as I have autopair for curly braces on. Would it be possible to change it to something that doesn't clash with autopairing curly braces?

**Comment by AndreaCrotti** [comment]
Yes sure we can change it, what about {- for example instead @kozross ?

**Comment by kozross** [comment]
Autopair for curly braces for me causes ```{``` to produce ```{}``` on my screen, so ```{-``` probably wouldn't help an awful lot. Yasnippet for C/C++ uses 'pragma' for this purpose, but even 'prag' would be enough for me  - it's still shorter, and much less annoying.
