### ISSUE TITLE
Indentation control and whitespace

### ISSUE THREAD

**Issue by mambolevis** [AndreaCrotti/yasnippet-snippets#128]
Hi, 

I am trying to setup the default snippet indentation (c++-mode). Yasnippet uses a default indentation based on tab-with 4 but my desired indentation is 2 spaces (I don't use tabs).  In order to illustrate the problem, the indentation of two clases are shown below:
![image](https://cloud.githubusercontent.com/assets/13024208/13327449/2daa3b80-dbea-11e5-81fc-abb36fe3379d.png)

The first snippet class indentation insert 4 spaces. The second snippet class insert one tab at class declaration level and two tabs at method declaration level. 
Default snippet indentations are marked using whitespaces package.

Questions:
1. Is it possible to change the default snippet indentation to 2 spaces?
2. How can I obtain the following desired indentation when inserting a snippet?

![image](https://cloud.githubusercontent.com/assets/13024208/13330185/ea2cb424-dbf7-11e5-8f79-b7eac89c9b11.png)

Thanks

**Comment by npostavs** [comment]
> Yasnippet uses a default indentation based on tab-with 4 but my desired indentation is 2 spaces (I don't use tabs).

I think Yasnippet should be using `indent-according-to-mode`, so you should get whatever settings you have setup for `c++-mode`.

**Comment by mambolevis** [comment]
Thank you!

**Comment by npostavs** [comment]
> Thank you!

Does that mean it's working correctly for you??

**Comment by mambolevis** [comment]
yes, it is working.
