### ISSUE TITLE
[Python] pyplot pl vs plt 

### ISSUE THREAD

**Issue by jtamagnan** [AndreaCrotti/yasnippet-snippets#129]
It seems like the standard way to import pyplot from matplotlib is:

``` python
import matplotlib.pyplot as plt
```

instead of:

``` python
import matplotlib.pyplot as pl
```

I believe that the pl snippet should be changed to reflect that.

I am basing this off of the [documentation](http://matplotlib.org/api/pyplot_api.html) and other general documentation. What do people think of this change?

**Comment by AndreaCrotti** [comment]
Yes that's what on the official docs anyway so thanks I changed it..
