### ISSUE TITLE
add es6 snippets

### ISSUE THREAD

**Issue by transtone** [AndreaCrotti/yasnippet-snippets#134]
please add js's es6 snippets like vsc:
https://marketplace.visualstudio.com/items?itemName=xabikos.JavaScriptSnippets

**Comment by AndreaCrotti** [comment]
I would probably not just copy things from another place since they have to work well with the existing snippets..
And I'm not really a JS developer so would not do it myself since I can't judge.
PR welcome of course ;)

**Comment by AndreaCrotti** [comment]
Quite a few things where merged already now related to this issue so I think it's fair to assume it can be closed now
