### ISSUE TITLE
Add typescript snipets

### ISSUE THREAD

**Issue by JAremko** [AndreaCrotti/yasnippet-snippets#139]
Emacs (Spacemacs/develop) has decent typescript support. The only missing thing for me is snippeting(snipping?).

**Comment by AndreaCrotti** [comment]
To be honest I don't work with Javascript and/or typescript so feel free to propose some snippets and I'll have a look.

They are really simple to write as you can see from the many examples we have in this repository.
Thanks

**Comment by FrancescElies** [comment]
Hi I would be interested in this too, what about starting with these ones https://github.com/bleggett/yasnippets-angular2 ? Would you welcome a PR?
