### ISSUE TITLE
cc/c++-mode overloaded keys

### ISSUE THREAD

**Issue by ennokde** [AndreaCrotti/yasnippet-snippets#145]
Leaving this here as a proposition and a request for comments.

Currently when you hit tab on `inc` in cc-mode it offers you both includes, system and local and you have to pick one. I fixed this for myself by changing them to `incs` and `incl`.
Same thing for `f` in c++-mode which stands for a function declaration or a member function definition. I would suggest replacing the member function definition key with `mf`.

There is no shortage of (meaningful) abbreviations in c/c++-mode so I dont think there is a need for these collisions. If I am not alone with this thought I  get a patch ready of course.

**Comment by nilsdeppe** [comment]
I agree with that there is no reason to have a collision in this case. I would love to see a patch so that by default `mf` is member function.

**Comment by AndreaCrotti** [comment]
seems reasonable to me, sure a pull request is welcome, thanks

**Comment by AndreaCrotti** [comment]
Closing this since it's already being taken care of in #159
