### ISSUE TITLE
C++ assignmen operator doesn't use copy-swap

### ISSUE THREAD

**Issue by DavidSnider** [AndreaCrotti/yasnippet-snippets#150]
I just noticed that the snippet for the assignment operator for c++ doesn't use the copy-swap idiom. Was that purposeful?

**Comment by AndreaCrotti** [comment]
I wasn't the original author and don't personally use C++ so probably not on purpose..
Feel free to make a PR if the copy-swap idiom is the right way to go..

**Comment by ennokde** [comment]
Using that would obviously require the type to be copyable and have a swap function which does not apply to every type out there.
The snippet should stay as it is but an additional one using copy-swap might be nice.

**Comment by AndreaCrotti** [comment]
Ok thanks, closing this then, I don't do much C++ but if anyone can point out exactly how this other snippet using copy-swap should behave I will happily add that as well.
