### ISSUE TITLE
How to discard the eval result of elisp code in a snippet ?

### ISSUE THREAD

**Issue by Yevgnen** [AndreaCrotti/yasnippet-snippets#160]
Hi !

I'd like to do something like `(require 'org-table)` in before/after loading a snippet. For example, I want to lazily load the package `org-table` before/after loading a snippet like

    `(require 'org-table)`
    `(orgtbl-mode 1)`
    % BEGIN RECEIVE ORGTBL ${1:table}
    % END RECEIVE ORGTBL $1
    #+ORGTBL: SEND $1 orgtbl-to-latex :splice nil :skip 0
    |$0

which is from [here](http://stackoverflow.com/questions/8513966/converting-an-org-mode-table-to-latex).

Wrapping the elisp code in a `, the eval result will be inserted in to buffer which is unexpected. How can I achieve this besides the before insert and after expand hooks ?

Thanks !

**Comment by npostavs** [comment]
Use an expression that evaluates to `nil`:
```
`(progn (require 'org-table) (orgtbl-mode +1) nil)`
% BEGIN RECEIVE ORGTBL ${1:table}
...
```

**Comment by Yevgnen** [comment]
@npostavs That's magic! Thanks! But the code line should move to suitable position because it will insert a blank line there.

**Comment by npostavs** [comment]
> But the code line should move to suitable position because it will insert a blank line there.

You could also move it outside of the snippet body, into `expand-env`:
```
# name: foo
# key: foo
# expand-env: ((_dummy (progn (require 'org-table) (orgtbl-mode +1))))
# --
% BEGIN RECEIVE ORGTBL ${1:table}
% END RECEIVE ORGTBL $1
#+ORGTBL: SEND $1 orgtbl-to-latex :splice nil :skip 0
|$0
```
