### ISSUE TITLE
adoc-mode snippets proposal

### ISSUE THREAD

**Issue by nicorikken** [AndreaCrotti/yasnippet-snippets#161]
I just ported the asciidoctor snippets, as defined for the Atom editor, to YASnippet. I've created a seperate [adoc-mode-yasnippet](https://github.com/nicorikken/adoc-mode-yasnippet) repo. The original snippets were defined [here](https://github.com/asciidoctor/atom-autocomplete-asciidoc/blob/master/snippets/language-asciidoc.cson).

If this meet the criteria for inclusion, I'd be happy to convert it into a PR.

**Comment by AndreaCrotti** [comment]
I never used asciidoc so can't judge too much but the snippets look perfectly fine to me.
Please open a pull request and I'll be happy to merge, thanks

**Comment by AndreaCrotti** [comment]
Closing this for now @nicorikken, happy to review a PR when you want
