### ISSUE TITLE
Using js2-mode in snippets for js-mode

### ISSUE THREAD

**Issue by Hardtack** [AndreaCrotti/yasnippet-snippets#165]
Since I'm using emacs for React development, I don't use `js2-mode` (Because it contains many bugs for parsing JSX). But js-mode of yasnippet-snippets does not works on `js-mode`.
When I don't load `js2-mode` emacs prints
```
[yas] Error in condition evaluation: Symbol’s function definition is void: js2-node-type
```
And when I load `js2-mode`,
```
[yas] Error in condition evaluation: No JavaScript AST available
```
It works after I turn on `js2-mode`.

Thank you for providing great set of snippets!

**Comment by AndreaCrotti** [comment]
Thanks for the report.
And what about js-jsx-mode by the way?

```js-jsx-mode is an interactive compiled Lisp function.

(js-jsx-mode)

Parent mode: ‘js-mode’.
```

**Comment by AndreaCrotti** [comment]
(which I personally never used tbh but might help you in this case, even if there is probably a bug with the snippets as well)

**Comment by AndreaCrotti** [comment]
@Hardtack do you still have this problem or maybe found a solution in the meanwhile?

**Comment by Hardtack** [comment]
Nope. I'm actually not using emacs these days.

**Comment by AndreaCrotti** [comment]
Ok I'll close then, thanks
