### ISSUE TITLE
multi key

### ISSUE THREAD

**Issue by avelino** [AndreaCrotti/yasnippet-snippets#214]
Today used `tr` to start `import pdb;...`, idea would be to have `tr` and put another key as  `pdb`

example:
```
# -*- mode: snippet -*-
# name: trace
# key: tr, pdb
# group: debug
# --
import pdb; pdb.set_trace()
```

or

```
# -*- mode: snippet -*-
# name: trace
# key: tr
# key: pdb
# group: debug
# --
import pdb; pdb.set_trace()
```

**Comment by AndreaCrotti** [comment]
That's an interesting idea @avelino however both these options are not supported by yasnippet at the moment.
(see http://joaotavora.github.io/yasnippet/snippet-development.html#sec-2-1 for more docs)
So if you want to propose something like that you should just do it in the `yasnippet` repository where they could potentially make it happen.
Thanks!
