### ISSUE TITLE
Latest version from MELPA does not install on Windows emacs

### ISSUE THREAD

**Issue by berhoel** [AndreaCrotti/yasnippet-snippets#223]
Installation of the latest version from MELPA on Windows emacs fails with:

   `File error: Opening output file, Invalid argument, c:/Users/berhol/AppData/Roaming/.emacs.d/elpa/yasnippet-snippets-20170920.1234/snippets/php-mode/foreach=>`

it seems `foreach=>` is not a valid file name.

**Comment by AndreaCrotti** [comment]
Thanks for the report @berhoel 
I've renamed the file, the next time Melpa builds it will be fixed! (should be daily I guess)

**Comment by AndreaCrotti** [comment]
I just had a look and there are other files with similar issues, like
```
operator!=
```
in C++ mode

Are they also a problem?

**Comment by berhoel** [comment]
`operator!=` is OK.

Trying to change a file name to `foreach=>` in the file explorer under Win7 I get a popup saying:

    A filname can't contain any of the following characters:
                      \ / : * ? " < > |

Thanks for your prompt reply.
