### ISSUE TITLE
Error when updating the yasnippet package from Melpa

### ISSUE THREAD

**Issue by AndreaCrotti** [AndreaCrotti/yasnippet-snippets#224]
I don't think this is really a bug with this package, but generally when a new version gets installed and you try to open a file you get an error like:

```
File mode specification error: (file-error Opening directory No such file or directory /home/andrea/.emacs.d/elpa/yasnippet-snippets-20170920.1234/snippets/js-mode)
yas--subdirs: Opening directory: No such file or directory, /home/andrea/.emacs.d/elpa/yasnippet-snippets-20170920.1234/snippets/js-mode```
```

After a `yas-reload-all` it's all sorted even though you still see this in *Messages*
```
[yas] Check your `yas-snippet-dirs': /home/andrea/.emacs.d/elpa/yasnippet-snippets-20170920.1234/snippets is not a directory
```

And looking at the `yas-snipppet-dirs` it contains both the hold and the new package paths.
I wonder if there is anything to alleviate this problem, the code I used for the discovery is basically the same used by the other snippet packages (even if I didn't notice the same issue there).
Any idea?

**Comment by AndreaCrotti** [comment]
@npostavs maybe did you notice the same issue?

**Comment by npostavs** [comment]
> maybe did you notice the same issue?

I'm afraid I'm still rather behind on things, I haven't started using the new setup. But this sounds like joaotavora/yasnippet#495, so could probably be fixed by setting `yasnippet-snippets-dir` to `".../snippets/"` and adding the *symbol* `yasnippet-snippets-dir` to `yas-snippet-dirs`.
