### ISSUE TITLE
License for snippets?

### ISSUE THREAD

**Issue by notetiene** [AndreaCrotti/yasnippet-snippets#233]
I was wondering if the snippets are also subject to the GPLv3 license.  I'm usually the first to ask for the GPL compliance, but it might not be a good idea to license snippets as GPL.

Of course, I don't think anyone would come and enforce their theoretical rights for that, but it might clear some confusion in the future.

**Comment by AndreaCrotti** [comment]
Well Melpa requires that actually, so there isn't really much I can do about it if we want to keep it on Melpa.
So yes they are subject to GPLv3 I guess, but I honestly doubt (hope) it could ever become an issue.

**Comment by npostavs** [comment]
AFAIK, they only require a GPLv3 *compatible* license, so a permissive license would be okay too. 

> So yes they are subject to GPLv3 I guess, but I honestly doubt (hope) it could ever become an issue.

Yeah, I feel like all the snippets are too small and/or based on their respective core language syntax to consitute copyrightable works.

**Comment by notetiene** [comment]
@npostavs True that most are too small for that.  But what if someone comes up with a big template that is more than 15 lines (something I consider copyrightable maybe)?
