### ISSUE TITLE
HTML Snippet Comments Incorrect

### ISSUE THREAD

**Issue by sshaw** [AndreaCrotti/yasnippet-snippets#238]
https://github.com/AndreaCrotti/yasnippet-snippets/blob/6b6dcd9eca4d6d3e982bbc241b51cd6562ef600e/snippets/html-mode/html

```html
#contributor : Jimmy Wu <frozenthrone88@gmail.com>
    #name : <html>...</html>
    # --
    <html>
        
    </html>
```

https://github.com/AndreaCrotti/yasnippet-snippets/blob/6b6dcd9eca4d6d3e982bbc241b51cd6562ef600e/snippets/html-mode/form

```html
#contributor : Jimmy Wu <frozenthrone88@gmail.com>
    #name :<form method="..." id="..." action="..."></form>
    # --
    <form method="" id="" action="">
        
    </form>
```

Surely there are others.

**Comment by AndreaCrotti** [comment]
Sorry I don't quite get what you mean, what's the problem with these snippets?

**Comment by sshaw** [comment]
The snippet inserts the above into the buffer.

**Comment by AndreaCrotti** [comment]
Sorry @sshaw I just saw it now, but I don't think there is anything wrong with these snippets and they work perfectly well for me.
What version of yasnippet/Emacs are you on (even if not sure that's the problem really it would be quite weird)?

I'll close this for now anyway, feel free to re-open if it still happens and you can give me more information to try to reproduce it.
