### ISSUE TITLE
Add this package to melpa stable

### ISSUE THREAD

**Issue by SerialVelocity** [AndreaCrotti/yasnippet-snippets#242]
It would be nice for this package to be in melpa stable as well.

Here's a link:
https://stable.melpa.org

**Comment by sten0** [comment]
Given Version: 1.0.3 is declared in [yasnippet-snippets.el](https://github.com/AndreaCrotti/yasnippet-snippets/blob/master/yasnippet-snippets.el) please consider tagging version 1.0.3 for consistency :-)
