### ISSUE TITLE
add HTML templating snippet

### ISSUE THREAD

**Issue by azzamsa** [AndreaCrotti/yasnippet-snippets#247]
I use mostly emmet-mode for this. But I am tired to type `{% foo %}` repeatedly. 
So I add new snippet to `snippets/html-mode/` wich will be inherited by web-mode.

I add 
```
# -*- mode: snippet -*-
# name: templateblock
# key: tpb
# --
{% ${1:text} %}
```

Can I make a PR for this ?, or any other thing I have to fix ?

Thank you.

**Comment by AndreaCrotti** [comment]
Mm is that actually valid HTML?
Isn't it one of the various moustache styles templating engine syntax?
Not sure it should be in HTML mode in that case imho.

**Comment by azzamsa** [comment]
> Mm is that actually valid HTML?

no :)

> Isn't it one of the various moustache styles templating engine syntax?

Yes. maybe I should put this on yas template engine syntax
