### ISSUE TITLE
.nosearch removed in melpa package

### ISSUE THREAD

**Issue by psidhu** [AndreaCrotti/yasnippet-snippets#273]
I installed yasnippet-snippets 20180422.649 in emacs 25.3.2 through package manager from melpa.

I get the error: Invalid Read Syntax: #

Looking into it, it's required that ``.nosearch`` exist so the loadpath doesn't confuse and override default.

My installed package does not have this, while I see in this repo that it exists. I've simply added it to my local ``yasnippet-snippets-20180422.649/snippets`` directory which works. I don't know how melpa packaging works, but it seems that ``.nosearch`` is simply stripped during this process.

See the following for reference:
* https://github.com/AndreaCrotti/yasnippet-snippets/issues/55

**Comment by AndreaCrotti** [comment]
This PR is now merged:
https://github.com/melpa/melpa/pull/5461
so hopefully we should not have the same issue anymore
