### ISSUE TITLE
The org-mode folder has to be moved inside snippets

### ISSUE THREAD

**Issue by daviderestivo** [AndreaCrotti/yasnippet-snippets#282]
Hi,

I think the org-mode folder in the root of the repo has to be moved into the snippets one.

![screen shot 2018-06-29 at 19 11 29](https://user-images.githubusercontent.com/16867449/42105522-e008590a-7bd0-11e8-9c95-29d41eee7a65.png)

Regards,
Davide

**Comment by daviderestivo** [comment]
Ciao Andrea,

I think instead of moving them you have deleted the two files.

Regards,
Davide

**Comment by AndreaCrotti** [comment]
Ah yes sorry @daviderestivo  I thought they were files I added by mistake sorry.
I've moved them to the right directory now, thanks for noticing

**Comment by daviderestivo** [comment]
Thanks Andrea.
