### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by oliveratutexas** [AndreaCrotti/yasnippet-snippets#289]
This might be useful as an integration into one or many of the spacemacs layers.

**Comment by AndreaCrotti** [comment]
Thanks for the suggestion.
I don't know much about spacemacs, but I can try to find out how we could do that.

**Comment by sdwolfz** [comment]
@oliveratutexas Spacemacs already has this package as part of the `auto-completion` layer on the `develop` branch, which will be released to master soon. You can use it right away by checking out that branch or you can wait another week to have it on master.

**Comment by AndreaCrotti** [comment]
Ah great thanks even better thanks
