### ISSUE TITLE
org mode prefers lowercase keywords now

### ISSUE THREAD

**Issue by memeplex** [AndreaCrotti/yasnippet-snippets#303]
Since some months ago the org mode codebase is preferring lowercase blocks and keywords. See for example [this commit](https://code.orgmode.org/bzg/org-mode/commit/13424336a6f30c50952d291e7a82906c1210daf0). Also, the template expansion based on 9.2 hardcodes `#+begin_/#+end_` in lowercase. Unfortunately, the snippets in this collection are all uppercase. Since there surely are and will be people that prefer the uppercase convention, what can be done to provide both options? Offer two sets of snippets?  In case of providing just one, it's going to be time to move to lowercase.

**Comment by memeplex** [comment]
See also http://lists.gnu.org/archive/html/emacs-orgmode/2019-02/msg00146.html

**Comment by equwal** [comment]
PERSONALLY I AM ALL FOR THE LOWERCASE CONVENTION, SINCE UPPERCASE CONVENTIONS ARE FALLING OUT OF STYLE EVERYWHERE.

[CONSIDER THIS ISSUE DEALT WITH, I THINK](https://github.com/AndreaCrotti/yasnippet-snippets/pull/322).

**Comment by AndreaCrotti** [comment]
This is now sorted
