### ISSUE TITLE
Latex Environment Snippets: Why there is \item inside the environment?

### ISSUE THREAD

**Issue by ofenerci** [AndreaCrotti/yasnippet-snippets#319]
When I look at the snippets (https://github.com/AndreaCrotti/yasnippet-snippets/blob/master/snippets/latex-mode/equation), 

 ```
# -*- mode: snippet -*-
# name: equation
# key: eq
# --
\begin{equation}
\item $0
\end{equation}

```

I wonder why there is extra \item inside the equation environment. `\item` is hardly used inside the equation environment.

**Comment by AndreaCrotti** [comment]
This is now gone, so can be closed, thanks @ofenerci
