### ISSUE TITLE
Org mode snippets have a number of problems, especially newlines

### ISSUE THREAD

**Issue by equwal** [AndreaCrotti/yasnippet-snippets#320]
These have been dealt with at my pull request https://github.com/AndreaCrotti/yasnippet-snippets/pull/321
Problems with Org snippets
=====
I just went through them all and have suggestions here, working on a pull request for them now.

Issue author: extra newline and whitespace at end of line
#+AUTHOR: asdf

Issue dot: Extra beginning of line whitespace
#+begin_src dot :file file :cmdline -Tpdf :exports none :results silent
                        
#+end_src

[[file:file]]

Issue img: newlines
<img src=""
alt="" align="left"
title="image title"
class="img"
</img>

UML: no issue
#+BEGIN_UML

#+END_UML

date: noissue
#+DATE: Year:month:day

issue email: should suggest user's email
issue links: newline after, spaces before
[[ external_link ][ Name of the link]

issue setup: newline after
#+SETUPFILE: 

issue style: newline after
#+STYLE: <link rel="stylesheet" type="text/css" href="" />

issue elisp: should alias emacs-lisp too

issue title: distracting default, newline after
#+TITLE: What the hell

issue author: newline after, shoud suggest user-full-name
#+AUTHOR: 

issue center: newline after
#+BEGIN_CENTER

#+END_CENTER

issue figure: newline
#+CAPTION: caption
#+ATTR_LaTeX: scale=0.75
#+LABEL: fig:label

issue images: two newlines after
#+caption: caption of the image
[[file:image_path]]

issue python: nl after
#+BEGIN_SRC python

#+END_SRC

issue videos: should highlight-to-delete the ## line
##videos must be used with an image..so when image is clicked video starts
[[link of the video][file:link of the image]

issue example: two newlines after
#+BEGIN_EXAMPLE

#+END_EXAMPLE

issue: newline
#+INCLUDE: 

issue ipython: newline
#+BEGIN_SRC ipython :session session01 :file ./ipython-7GOBIG.png :exports both

#+END_SRC

issue opython: newline
#+OPTIONS: H:1 num:t||nil toc:t||nil

issue keywords: newline
#+KEYWORDS: org-mode

issue language: two newlines
#+LANGUAGE: en

issue description: two nls
#+DESCRIPTION: description of your org-mode file

issue user's email: why parens on the name?
issue current time: why parens on the name?
Wed Jun 19 13:39:50 2019

**Comment by equwal** [comment]
https://github.com/AndreaCrotti/yasnippet-snippets/pull/321

**Comment by AndreaCrotti** [comment]
So we can close this now right @equwal ?

**Comment by equwal** [comment]
> So we can close this now right @equwal ?

Yes!
