### ISSUE TITLE
yasnippet-snippets.el has bug

### ISSUE THREAD

**Issue by nicolas4d** [AndreaCrotti/yasnippet-snippets#335]
;;;###autoload
(defun yasnippet-snippets-initialize ()
 "Load the `yasnippet-snippets' snippets directory."
 (add-to-list 'yas-snippet-dirs yasnippet-snippets-dir t)
  (yas-load-directory yasnippet-snippets-dir t))
above function has little bug.

this line:
(add-to-list 'yas-snippet-dirs 'yasnippet-snippets-dir t)

recomended :
(add-to-list 'yas-snippet-dirs yasnippet-snippets-dir t)

there is ' before yasnippet-snippets-dir variable.

please tell me.
is this is bug?

**Comment by npostavs** [comment]
No, it's not a bug. If you look at the doc for `yas-snippet-dirs`, it says elements should be "a string **or a symbol whose value is a string**". So `(add-to-list 'yas-snippet-dirs 'yasnippet-snippets-dir t)` is the way to add a value of the second kind.

**Comment by nicolas4d** [comment]
> No, it's not a bug. If you look at the doc for `yas-snippet-dirs`, it says elements should be "a string **or a symbol whose value is a string**". So `(add-to-list 'yas-snippet-dirs 'yasnippet-snippets-dir t)` is the way to add a value of the second kind.

thank you for  response!
you let me learn some important!
