### ISSUE TITLE
python-mode snippets are expanded with wrong indentation if there is more than one level of indentation possible in the snippet

### ISSUE THREAD

**Issue by lgp171188** [AndreaCrotti/yasnippet-snippets#34]
Please refer to https://github.com/capitaomorte/yasnippet/issues/485 for more background information and the discussion that happened there. The issue happens because of python snippets having more than 1 level of indentation not having `# expand-env: ((yas-indent-line 'fixed))` as per the yasnippet maintainer. This causes the snippet to be expanded with wrong indentation and hence wrong code. He pointed me to this repository and told that the fix has to be made in this repository. I have tested the changes by manually editing the snippet to add the `# expand-env: ((yas-indent-line 'fixed))` line and I can see that the expansion works fine after that.

This issue happens only with snippets with more than one possible level of indentation.

**Comment by bronger** [comment]
FIWI, I observe the wrong indentation with try/except, using current Git Emacs (and thus, Python mode).  Haven’t tried older Emacsen, though. My snippets directory is called `elpa/yasnippet-snippets-20210408.1234/snippets/python-mode`. My .emacs does not contain yasnippet-related thing, apart from those inserted by the package manager.

**Comment by bronger** [comment]
If I insert `# expand-env: ((yas-indent-line 'fixed))` in the file `try`, it works fine.
