### ISSUE TITLE
python-mode init snippet unexpected docstring

### ISSUE THREAD

**Issue by iliakur** [AndreaCrotti/yasnippet-snippets#386]
Hi!

Thanks for the package, it helps with work a lot.

I've used the `init` snippet for python-mode a few times and was surprised by the docstring that it generates. For some reason it's only single quotes.

Is this a bug? If not, what is the intended behavior? For instance, do we expect it to call the `doc` snippet for the docstring?

If it's a bug, I'd volunteer to fix it :)

Thanks in advance!

**Comment by AndreaCrotti** [comment]
I think it's just because there is also another snippet `init_docstring` with some a smarter docstring generation.
Does that help @iliakur ?

**Comment by iliakur** [comment]
Ah, didn't see that one. Yes, all good, thanks :)
