### ISSUE TITLE
kotlin-mode main snippet is wrong

### ISSUE THREAD

**Issue by marcos-cezar** [AndreaCrotti/yasnippet-snippets#394]
When you use main snippet on kotlin-mode the code expansion results in:

fun main(args: Array<**s**tring>) with lowercase "s".

The correct expansion must be: 

fun main(args: Array<String>) with upcase "s"

**Comment by AndreaCrotti** [comment]
I don't use Kotlin myself, would you like to make a PR to fix it @marcos-cezar ?

**Comment by AndreaCrotti** [comment]
Ah nvm I just saw the PR and merged https://github.com/AndreaCrotti/yasnippet-snippets/pull/395
Thanks!
