### ISSUE TITLE
Compile warnings while installing

### ISSUE THREAD

**Issue by jcs090218** [AndreaCrotti/yasnippet-snippets#398]
I am getting these warnings during the installation. 😕 

```
In end of data:
snippets/bibtex-mode/.yas-setup.el:4:1:Warning: the function
    `yasnippet-snippets--no-indent' is not known to be defined.

In end of data:
snippets/python-mode/.yas-setup.el:39:1:Warning: the function
    `yasnippet-snippets--fixed-indent' is not known to be defined.
```

**Comment by AndreaCrotti** [comment]
Uhm I guess the function is not available at compile time but it's not actually an issue since it works at run-time.
Not sure how to hide the warning, any idea @npostavs maybe?

**Comment by npostavs** [comment]
I think `(require 'yasnippet-snippets)` in the `.yas-setup.el` files would do it.
