### ISSUE TITLE
org-mode, src(<src) snippet doesn't work properly

### ISSUE THREAD

**Issue by tttuuu888** [AndreaCrotti/yasnippet-snippets#402]
Thanks for this great package!

With Org mode version 9.4, `src` snippet doesn't work properly.
When type `<src` and `M-x yas-expand`, warning "org-edit-src-code: No such language mode: nil-mode" occurs.
Then cursor doesn't point `#+begin_src [HERE]`, but instead `[HERE]#+begin_src`

I think this has to do with update of org-mode.

Thanks.

**Comment by insanya** [comment]
Hello,
Org mode version 9.3 has the same problem. Running on Emacs 27.1.

**Comment by AndreaCrotti** [comment]
Uhm I just tried it now and it works fine for me I wonder what could be the difference, the snippet itself is very simple.
Do you have a full stack maybe?

**Comment by insanya** [comment]
Hi,
I'm new to debugging Emacs but i think this is it. xd
Let me know otherwise.
Tks!

[debug.txt](https://github.com/AndreaCrotti/yasnippet-snippets/files/5563421/debug.txt)

**Comment by tttuuu888** [comment]
@lrpereira Thank you for the information. It solves the problem.
I will close this issue. Thank you.
