### ISSUE TITLE
The package works correctly after I installed it but if I restart emacs no snippets is found.

### ISSUE THREAD

**Issue by falematte** [AndreaCrotti/yasnippet-snippets#423]
After installing the package I can found all the snippets with ivy-yasnippets. If I restart emacs no snippets is found.

**Comment by nimaipatel** [comment]
I'm facing the same problem. How did you solve this?

**Comment by falematte** [comment]
I had a missconfigured .emacs file. Try to start with a clean configuration.

**Comment by nimaipatel** [comment]
I'm using `use-package` and this is the relevant part of my configuration file. Is there anything that I'm doing wrong, I've only started using Emacs since 3 days?

```
  (use-package yasnippet
    :ensure t
    :config
    (progn (yas-global-mode)))

  (use-package yasnippet-snippets
    :after yasnippet
    :ensure t)
```

**Comment by AndreaCrotti** [comment]
My config is this atm:

```
(use-package yasnippet-snippets)

(use-package yasnippet
  :custom
  (yas-verbosity 2)
  (yas-wrap-around-region t)

  :config
  (yas-reload-all)
  (yas-global-mode))
```

even though maybe yas-reload-all should not be necessary ideally, there might be a smarter way but that works.

**Comment by nimaipatel** [comment]
Well I copied this as it is, but reloading my config seems to just remove all the snippets for some reason. It is probably something else in my config that is messing with it. I'll try debugging it when I have some time. Thanks anyway though!
