### ISSUE TITLE
Mentioning NonGNU ELPA

### ISSUE THREAD

**Issue by phikal** [AndreaCrotti/yasnippet-snippets#427]
Hi,

yasnippet-snippets have just been added to [NonGNU ELPA](https://elpa.nongnu.org/) yesterday: https://elpa.nongnu.org/nongnu/yasnippet-snippets.html

As you might know, {NonGNU,GNU} ELPA distributes stable versions by default, and these are determined by those commits that increment the version-tag in the package header. For that reason, the current version of the package is 0.2, as the version tag has not been bumped in a while. If you are interested in having yasnippet-snippets available via NonGNU ELPA, could you update the version tag when you prepare the next release?

Otherwise, it would be great if you could mention the NonGNU in the README, e.g. by adding the badge from the above link.

**Comment by AndreaCrotti** [comment]
Ok thanks, I've added the badge @phikal 
I'll release a new version when I fix a few open issues that are currently open.

**Comment by AndreaCrotti** [comment]
Ok @phikal after this massive PR https://github.com/AndreaCrotti/yasnippet-snippets/pull/429
I pushed a new version 1.0,
That should be fine right?
Thanks

**Comment by phikal** [comment]
You still would have to bump the [version tag](https://github.com/AndreaCrotti/yasnippet-snippets/blob/master/yasnippet-snippets.el#L7).

**Comment by AndreaCrotti** [comment]
Ah yes thanks fixed @phikal
