### ISSUE TITLE
Tag new stable release?

### ISSUE THREAD

**Issue by sten0** [AndreaCrotti/yasnippet-snippets#450]
Hi @AndreaCrotti,

How is the master branch these days?  Release ready?  There's another Debian release coming up and the deadline for importing a new version of yasnippets-snippets will be late January or so.  Currently we have v1.0, which is kind of old for the upcoming release,  No rush or pressure, it's just that some people complain we have old software, and I think that's often as much a case of lack of communication as available free time.

Cheers,
Nicholas

**Comment by AndreaCrotti** [comment]
Hi @sten0, it's fine to cut a new release now if you want 👍

**Comment by sten0** [comment]
Hi @AndreaCrotti,

Thank you for the ACK :)  Unfortunately #326 has become a hard blocker rather than a warning due to stricter application of the [DFSG](https://en.wikipedia.org/wiki/Debian_Free_Software_Guidelines), since html is almost always an output format these days.  I can also cut the file from the source used in Debian.  That file almost a year out of date btw.
