### ISSUE TITLE
There should be no org-mode snippet using common names as key

### ISSUE THREAD

**Issue by fniessen** [AndreaCrotti/yasnippet-snippets#69]
For the exact same reason as the one developped in https://github.com/AndreaCrotti/yasnippet-snippets/issues/52 (i.e., when one binds `yas-expand' to SPC -- that is the "abbrev-way"), there should be no standard word of the dictionary used as "snippet keys".

In Org-mode, there are quite a few: "code", "dot", "embedded", "entry", "figure", "latex", "matrix" and "verse".

Could these be replaced by "non-word" abbreviations, so that YASnippet does not pop up at unexpected times (when typing "you can see in the code that...", for example)?

Thanks!

**Comment by AndreaCrotti** [comment]
Yes ok I'll remove them as well

**Comment by fniessen** [comment]
Excellent news!  Can you ping capitaomorte once it's done, so that he knows he has to update your project?  Thanks...

**Comment by omajid** [comment]
Please reconsider adding back the src snippet (with another name, if appropriate). I use org-mode with embedded source code and the removal of this snippet makes it more cumbersome to write that source code - I have to recall the entire syntax every time I want to use it.

**Comment by fniessen** [comment]
@omajid The problem I point here is using common names as abbrev names. For the rest, of course, I don't mind having abbrevs!

Note, though, that it's easier IMHO to use "<s" followed by TAB to create a source code block in Org. And, even better, type your code, select the region, and then use C-c C-v C-d (demarcate the code block).

See http://org-babel.readthedocs.org/en/latest/key-bindings/, section "Edit the code" for more information.
