### ISSUE TITLE
"for" loop snippet doesn't expand properly

### ISSUE THREAD

**Issue by YorkZ** [AndreaCrotti/yasnippet-snippets#78]
The following is my snippet. It's basically a copy from the existing snippet
`for' with a new name "forr".

    # -*- mode: snippet -*-
    # name: forr
    # key: forr
    # --
    for (${1:i = 0}; ${2:i < N}; ${3:i++}) { $0 }

In a C++ buffer, when typing "forr", it expands to the following:

    for (|)i = 0; i < N; i++) {

    }

`|' is the position of the point after expanding the snippet. Hitting TAB wouldn't goto the next field.

The problem won't show up if I either turn off `auto-complete`, or turn off `smartparen`. Therefore, this might not be a problem of yasnppet. If that's the case, my apology.

This problem is really painful, and I would appreciate any help.

Thanks

**Comment by AndreaCrotti** [comment]
Mmm I don't understand what is going on, I have both auto-complete and smartparen on and it works perfectly fine for me.

All other snippets work fine?
I'm not sure what it could be otherwise, need more information and your Emacs configuration for some hope to be able to reproduce it.

**Comment by YorkZ** [comment]
Hi AndreaCrotti,

Thank you very much for looking into this issue. Please refer to [my post here](https://github.com/auto-complete/auto-complete/issues/379#issuecomment-72143616) for more detailed information. Also, [stardiviner](https://github.com/auto-complete/auto-complete/issues/379#issuecomment-72302267) experienced the same problem.

The exact same snippet named `for` doesn't have problem.

Below is part of my configuration:

    (require 'yasnippet)

    ;;; My snippet directory
    (defvar yz/yasnippet-dir
      (expand-file-name "yas-snippets" user-emacs-directory))

    ;;; Change variable default values
    (setq yas-snippet-dirs (cons yz/yasnippet-dir yas-snippet-dirs)
          yas-also-auto-indent-first-line t
          yas-wrap-around-region t)

The `forr` snippet is in the directory `yz/yasnippet-dir`. Please let me know if I can be helpful.

Thanks

**Comment by YorkZ** [comment]
Finally, the problem has been found to be an `ac-complete advice` in `smartparens.el`. The problematic advice has been removed from `smartparens.el`. Sorry for suggesting the possibility in Yasnippet.
